### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by grunberg** [hrjakobsen/slext#10]
pls do not fak up myy design

**Comment by Hense94** [comment]
I feel as if the developers of this otherwise great plugin which allows for an extraordinary number of taabs to stay open at any one time, shouldn't let just anyone open issues on their GitHub, as some of these issues aren't very serious.

**Comment by grunberg** [comment]
I feel as if the developers of this amazing plugin which allows for a multitude of taabs to be opened in ShareLatex really hit the nail on its head with this added feature. Who doesn't love a little heart on their taab?
