### ISSUE TITLE
Tabs are not working and color of layout can't be changed

### ISSUE THREAD

**Issue by svanheijst** [hrjakobsen/slext#102]
I'm using the chrome extension for SLext, downloaded via the extension store. On the 4th of July everything still worked fine. But when I tried again yesterday (30/8/23) the extension is no longer working properly. The extension does seem to initiate, as the colours change from the basic green to red. But there is no way to change the layout colours after, and most importantly tabs are no longer opened when switching between files within a project.

Tested to see if the problem was due to my browser, but using Firefox (also on a different laptop) gave the same problems. Also reinstalling google chrome or the extension didn't work.

I hope this project is still active and the problem can be solved, as I really love to keep on use the features it offers.

**Comment by hrjakobsen** [comment]
Hi there. The extension may need to be updated due to recent changes. I'll have a look later today. Thanks for reporting it!

**Comment by hrjakobsen** [comment]
I've just submitted a new version to both webstores. The fixed version should land soon. Please let me know if version 1.7.1 doesn't solve your issue.

**Comment by svanheijst** [comment]
I just tested the new version of the extension on both google chrome and firefox, and it is working perfectly again. Thanks for resolving the problem so quickly.
