### ISSUE TITLE
Tabs are gone

### ISSUE THREAD

**Issue by Frendrup** [hrjakobsen/slext#103]
Tabs are gone, don't know the reason 
Using Google Chrome and Windows 10

First observed 19-02-2024 when opening another project. 
Prior to opening the project without the tabs, I had two projects open with the tabs still showing and working, however they were not loaded in the newly opened project

Chrome has now restarted and update to Version 121.0.6167.185 (Official version) (64-bit) and tabs are still gone.
Image for reference

Am I missing a setting to be toggled?

![image](https://github.com/hrjakobsen/slext/assets/24384659/015c520f-3b5c-4d45-a92f-212b72102f9e)

**Comment by hrjakobsen** [comment]
Thanks for reporting this @Frendrup. Some Angular code that SLext was relying on has been removed. I think I can restore the functionality though. I'll have a go and get back to you.

**Comment by hrjakobsen** [comment]
I believe I have restored most of the functionality in https://github.com/hrjakobsen/slext/commit/1b6da8a091cad2b24aeb08ed8c7c065268a0a6ee. There's currently a bug where it will only re-index files when loading the page. So if you add a new file and navigate to it, it won't open a new tab. It seems to be a limitation of the way we're reading the list of files. This is certainly better than it being completely broken, so I'll make a new release with these fixes.
