### ISSUE TITLE
Opening too many tabs, makes them go outside the screen

### ISSUE THREAD

**Issue by Hense94** [hrjakobsen/slext#17]

**Comment by anton-christensen** [comment]
The tab-bar is scrollable

**Comment by hrjakobsen** [comment]
Doesn't work on desktop PC, we have do enable scrolling sideways without showing the scrollbar

**Comment by grunberg** [comment]
Donneren var for hurtig, Anton!

**Comment by hrjakobsen** [comment]
Working implementation in 9d4ff90eb43744cf60497e0f6f295a06c944d16d. Still needs polishing though. Maybe a job for @anton-christensen ? :smile:

**Comment by hrjakobsen** [comment]
![selection_111](https://cloud.githubusercontent.com/assets/3295293/20410487/94e00c1c-ad1d-11e6-8f8f-c6c43ca3ba33.png)

**Comment by anton-christensen** [comment]
polish applied #77723d
