### ISSUE TITLE
Invisible scroll bar (perhaps because of grey-on-grey colours?)

### ISSUE THREAD

**Issue by grunberg** [hrjakobsen/slext#29]
![image](https://cloud.githubusercontent.com/assets/15012863/24600013/14029c9e-1853-11e7-9395-5e1e5db1f1b5.png)
As seen on the image, there is no visible scroll bar, even though it does work. My guess is that someone with little to no design experience accidentally made a grey-on-grey colour choice.

**Comment by Hense94** [comment]
It is sad that people with little to no design experience are allowed to work on such important projects as SLext™.

**Comment by hrjakobsen** [comment]
What color theme are you using?

**Comment by grunberg** [comment]
katzenmilch, but even with darker themes such as terminal, it still does not work

**Comment by hrjakobsen** [comment]
What SLext color theme? The one in the "SLext Settings" menu.

**Comment by grunberg** [comment]
The white-red-grey option, changing it to black-red-grey solved the problem, thanks!

**Comment by hrjakobsen** [comment]
This was a bug in the SettingModule where the colors of the scroll-bars where not being set to any values. This was corrected in 7a39b38aac407bd506bf86cd66d1edd95570b275
