### ISSUE TITLE
Custom commands?

### ISSUE THREAD

**Issue by Diamundo** [hrjakobsen/slext#35]
Hi,

I find myself using the `\emph{}` command a lot, but ShareLaTeX doesn't have a command for it.
My workaround is to `Ctrl+I` italize it, then `Ctrl+<` 3x to go to the end of `\textit` | `{text}`, then `Ctrl+Shift+<` to select the `textit`, then type `emph` to replace it.

What if there was a SLext custom command to do this, like `Ctrl+E` (opens Chrome search bar) or `Alt+E` (opens Chrome 'more options' three-dots window top-right) ?

Perhaps this should be split into two issues:

1. \emph Command
2. Custom commands

And I understand that as a programmer, grabbing the selected text inside ShareLaTeX is a lot of work, and defining custom commands even more difficult. 
Just curious to hear your thoughts!

**Comment by hrjakobsen** [comment]
This should be possible as we have access to the ace editor field. We could add extra commands to the editor, that would wrap the selected text in a LaTex command. Setting custom commands requires a bit more work, as the settings menu must be updated a menu for creating the shortcuts. I will keep this in mind when I next update SLext.

**Comment by Diamundo** [comment]
I like it! It saves time comparing to how I used to do it, and seems really powerfull!
Quick question, can I also undo it with `Ctrl+Z` as I would undo for example a `Ctrl+I` ?

**Comment by hrjakobsen** [comment]
Sounds good! 

Yes, it can be undone the same way as `Ctrl+I`.

**Comment by hrjakobsen** [comment]
Implemented in 1191fcd949440bdeb736a47e1499f8d0394a7b68 and will be merged into master when tested.
