### ISSUE TITLE
SLext does not works with projects shared through links, only invites

### ISSUE THREAD

**Issue by RasmusBarrett** [hrjakobsen/slext#37]
You can share a Sharelatex project in two ways.
First you can share the project with a invite to a email. Here SLext works as the URL becomes https://www.sharelatex.com/project/.. as it is put in your own project folder.
However if a project is shared through link you only can get access to, and it is not in your personal folder. So the URL is https://www.sharelatex.com/.. and SLext does not work.

**Comment by hrjakobsen** [comment]
Okay, so we have links on 3 different forms:

- http://sharelatex.com/project/sdal124msl19djxwofjso
- http://sharelatex.com/8392847589xxdjldfjcjlp
- http://sharelatex.com/read/pojdnxkhgrjt

The first and third are easily identified. I'm not sure how we should match the second one.

**Comment by hrjakobsen** [comment]
It seems as the second form can be described by the regular expression `[0-9]{10}[a-z]{12}`. I have tested on a few projects where it seems to fit. Can you test this on your project as well @RasmusBarrett ?

**Comment by hrjakobsen** [comment]
I have implemented the above in 5f8e342ec23, I will do some more testing before merging into the master branch.

**Comment by hrjakobsen** [comment]
This has been merged into master, as well as pushed to the chrome webstore.
