### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by Hense94** [hrjakobsen/slext#39]
I think it would be a great feature, if it was possible to count the number of characters or words in a selection by using a hotkey.
I would suggest _Alt + C_, but it is already used for what I'm guessing is **C**ommand.

**Comment by hrjakobsen** [comment]
How do you count words in a LaTeX document though?

`Lorem ipsum \emph{dolor sit amet}, \input{file.tex} adipiscing \color{blue}{elit}.`

- Words separated by spaces: 8
- Words separated by spaces, commands ignored: 9
- Words rendered when compiled: 7

Same with characters
- Characters if counted: 82
- Characters rendered when compiled: 44

**Comment by Hense94** [comment]
I would like to use it to get the exact amount of characters in my current selection. 

# Who's with me SLext'ers???!!!!!

**Comment by hrjakobsen** [comment]
Was implemented in 49e70a9 as part of the transition to a command palette instead of search-box. It can be used by selecting the text you want to count, pressing CTRL + P and the searching for and selecting "Character Count".
