### ISSUE TITLE
Custom command: behaviour cases

### ISSUE THREAD

**Issue by Diamundo** [hrjakobsen/slext#41]
As a follow-up for #35, where the feature was first discussed, I've seen the following behaviour:

- Alt + C when nothing is selected, and enter a command: freezes the cursor after the closing bracket (unreproducible, might've been user error or something.)

- Alt + C when nothing is selected, enter a command and press enter: inputs the command correctly, but puts the cursor _behind_ the closing bracket, whereas I would expect it between the brackets to enter text.

- Alt + C when nothing is selected, enter **no** command and press enter: inputs ```{}``` on the place of the cursor, and puts the cursor, again, _behind_ the closing bracket, whereas I would expect either an error or no brackets inserted.

- Alt + C when text is selected, either a command is entered or nothing is entered: only brackets are inserted, and cursor is directly behind the opening bracket, where I would expect the cursor directly behind the _closing_ bracket so you can continue typing.

What are your thoughts about the above behaviour?
(My thanks for implementing the feature, by the way, keep up the good work!)

I've also taken the liberty of looking at the sourcecode and I've made a few changes [in my fork](https://github.com/Diamundo/slext), ~~though I'm unable to compile (on a windows machine, don't currently have access to my NAS and am not sure if I've got the commands right). If you want me to make a pull request, let me know!~~ and I've compiled and tested it on my NAS. Pull request #42 has been made!

**Comment by hrjakobsen** [comment]
As you have made the pull request, I will close this issue and respond on the pull request instead.
