### ISSUE TITLE
Slext disable symbol input through CTRL+ALT+NumKey 

### ISSUE THREAD

**Issue by RasmusBarrett** [hrjakobsen/slext#43]
Slext uses the CTRL+ALT+Num (1..9) to switch between tabs, making it impossible to easy write symbols such as @ £ $ { [ ] through the keyboard when using slext. Small irritation when writting code in sharelatex.

**Comment by hrjakobsen** [comment]
I will fix this asap.

**Comment by hrjakobsen** [comment]
I have pushed an update to Chrome webstore, that should fix this. It will be published in less than an hour.

**Comment by RasmusBarrett** [comment]
It is working :-)
