### ISSUE TITLE
add keyboard bindings to go to PDF/code location

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#49]
Can be done using

```js
function goToPdfLocationInCode() {
  document.querySelector('.synctex-control-goto-code').click()
}

function goToCodeLocationInPdf() {
  document.querySelector('.synctex-control-goto-pdf').click()
}
```

**Comment by hrjakobsen** [comment]
I'm closing a bunch of issues that has to do with keyboard shortcuts. With the current implementation of keyboard shortcuts they are not really feasible to implement without running into a bunch of conflicts with other keybindings. If a more robust system is added for shortcuts we can revisit these issues (#49, #50, #51, #58).
