### ISSUE TITLE
go to last edit location

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#53]
I'd like to be able to move the cursor to (my) last edit location (in the editor) using keyboard bindings (e.g. Ctrl + Shift + Backspace).

**Comment by hrjakobsen** [comment]
Generally I've avoided touching the Ace-editor, since changes here could break the document themselves, which requires very intensive testing, to not accidentally induce unwanted changes into people's documents. This also applies to #54 .

**Comment by maiermic** [comment]
That means, a safe way to move the cursor is required in both cases. Am I right?

**Comment by hrjakobsen** [comment]
You could make some of the features without even touching the editor window itself. Overleaf saves last edit location for each file, so a file history would give you the ability to continue working in the last file you had open. Other than that, you would need to change locations in the editor itself, and implement a messaging system that different modules could send a message to whenever an action that should be considered happens.

**Comment by maiermic** [comment]
Where does Overleaf save last edit location for each file? How can I open one?
