### ISSUE TITLE
add keyboard bindings to switch to previous/next tab

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#58]
Add keyboard bindings similar to `Ctrl + Tab` (browser tabs) to switch to previous/next (Overleaf project file) tab.

**Comment by hrjakobsen** [comment]
What do you think will be good keyboard bindings?

Alt+left / Alt+right are used by the editor
Alt+n / Alt+p are used by slext (Alt+p at least)
Alt+tab / Alt+shift+tab are used by the browser

**Comment by maiermic** [comment]
How about `Alt + T`?
