### ISSUE TITLE
what is the difference between favorite and main tab

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#59]
The SLext Settings dialog shows keyboard bindings to set a tab as favorite/main tab. What is the difference between favorite and main tabs? How are they supposed to be used? Does it change any behavior or only show an icon on the tab? There is an option "Keep main tab first in tab bar" that changes the behavior of the main tab. Is there something else special about the main tab?

A description of main and favorite tabs should be added to the SLext Settings dialog.

**Comment by hrjakobsen** [comment]
Before temporary tabs were added, only favorite tabs (and main tabs) were persistent across reloads. Favorite tabs today is quite obsolete. The only difference between a favorite and non-favorite tab is that favorite tabs cannot be closed. 

Main tabs are special in that there can be only one, and that the main file is what is used in the "compile main" feature.
