### ISSUE TITLE
Compile all shortcut

### ISSUE THREAD

**Issue by anton-christensen** [hrjakobsen/slext#6]
Jesper request

**Comment by Hense94** [comment]
I feel as if the developers of this otherwise great plugin that allows a plethora of taabs to be open at once, have really dropped the ball here. My name is and never will be Jesper!

**Comment by hrjakobsen** [comment]
Alt-m now selects a "main" document
![selection_102](https://cloud.githubusercontent.com/assets/3295293/20322358/03772e9a-ab79-11e6-876d-2c94a326acf6.png)
Clicking on the new "Compile main" button will compile from the previously selected "main" document.
![selection_103](https://cloud.githubusercontent.com/assets/3295293/20322357/036fd3e8-ab79-11e6-85ee-2c2a3430d0fb.png)
