### ISSUE TITLE
buttons to switch tabs do not work

### ISSUE THREAD

**Issue by maiermic** [hrjakobsen/slext#61]
I expect the buttons with class `slext-tabs__caret--next` and `slext-tabs__caret--prev` to change the active tab (next/previous), but they only scroll left/right.

**Comment by hrjakobsen** [comment]
They do work as intended. The buttons shows the next and/or previous set of tabs. I will close this issue, as I don't see any problem to be solved. Switching to the next tab is already tracked in #58.

**Comment by maiermic** [comment]
I see. I misinterpreted this function.
