### ISSUE TITLE
Overview is default theme

### ISSUE THREAD

**Issue by joandrsn** [hrjakobsen/slext#68]
In the overview of current projects, the theme is the default theme.
I expected it to be the theme that I configured in the SLext Settings.
![overview](https://user-images.githubusercontent.com/5766695/69049055-4b213780-09ff-11ea-9733-3c6c14588b03.png)
![inside_proj](https://user-images.githubusercontent.com/5766695/69049057-4b213780-09ff-11ea-82a5-13d31baa98c1.png)

**Comment by hrjakobsen** [comment]
![image](https://user-images.githubusercontent.com/3295293/69058674-62b6eb00-0a14-11ea-8d05-cc1f9b6761e4.png)

Overleaf themselves do not change the appearance of the project listing, based on the "Overall theme" project setting. So SLext should probably not load any CSS at the project list at all.

**Comment by hrjakobsen** [comment]
In 6a450d3 I've made it so that the theme is only loaded when editing a project, and SLext will not change the appearance of the project overview page.
