### ISSUE TITLE
Tabs are not working

### ISSUE THREAD

**Issue by hrjakobsen** [hrjakobsen/slext#77]
After an Overleaf update brought a new implementation of the file tree, written in React rather than AngularJS, the tabs are no longer working. 

The first problem is that the class names in the DOM has changed, which wouldn't be a problem to solve. The more serious issue is that the DOM now only contains the visible files.

Compare the two DOMs below:

![Screenshot from 2021-02-10 10-45-42](https://user-images.githubusercontent.com/3295293/107500087-ace23a00-6b8d-11eb-8317-b24aaa54fe63.png)

After expanding the directory, a new `<ul>` element is added containing the remainder of the tree.

Obtaining a list of the available files in the project is not difficult, as they are stored in `select[name="rootDoc_id"]`, but as no buttons are available in the DOM, openining a file would have to open all directories in the path, and such expand all the relevant directories, which is a bit cumbersome, but could be the only solution.

**Comment by timothee-alby** [comment]
Hello, Overleaf developer here.

Indeed we're in the process or rewriting the Overleaf frontend in React and unfortunately we cannot support all existing unofficial extensions while doing so :(

Tip: `_ide.$scope.$emit('entity:selected', {type: 'doc', id:'DOC_ID'})` might be a workaround. Sadly we'll probably break this again soonish as we're progressively removing our Angular code...

I'm afraid I cannot provide much more help.
I've added a vote for this feature in our ideas tracker.

**Comment by hrjakobsen** [comment]
Hi Timothée, thanks for your response. 

I'll look into the workaround, thanks for the tip. Hopefully I can keep patching the features until the React rewrite settles and more "permanent" solutions can be found. 

Best of luck with the rewrite

**Comment by hrjakobsen** [comment]
Thanks to the tip provided by Timothée, I have managed to get tabs to work almost as they did before. They now only show up for documents (text files) and not binary files. The same holds for the file search feature, it only considers text files.
