### ISSUE TITLE
Compile and compile main button texts are invisible until hover over

### ISSUE THREAD

**Issue by Lightningblade** [hrjakobsen/slext#81]
This issue did not exist yesterday. I am also not the only one that has this issue since today.

![image](https://user-images.githubusercontent.com/30607152/111774677-143b8a00-88b0-11eb-803f-9fc33d769291.png)

![image](https://user-images.githubusercontent.com/30607152/111774685-17cf1100-88b0-11eb-860a-3af4c7a776e8.png)

**Comment by hrjakobsen** [comment]
Interesting. They must have changed something in the stylesheet since yesterday. I'll have a look.

**Comment by hrjakobsen** [comment]
I've submitted a fixed version to both chrome webstore and firefox addons.
