### ISSUE TITLE
Feature suggestion: PDF placement

### ISSUE THREAD

**Issue by tobiasrenkin** [hrjakobsen/slext#86]
- It would be really nice if it were possible to place the PDF on the left instead of the right of the overleaf window
- Or even better, to have the PDF open in a separate window that users can put wherever they like

Background: I use two monitors and I would like to have the PDF open the display to my left and the text on the display to my right. I have been bugging overleaf devs for better multimonitor support for years, but they don't seem to care much about this.

Thanks!

**Comment by hrjakobsen** [comment]
> Or even better, to have the PDF open in a separate window that users can put wherever they like 

Wouldn't we all? 😔

This is something that I have been working on previously, but without intercepting the websocket traffic between the client and server it is not very easy to do it well. Personally I would be fine with losing "jump to source" by having the pdf in a separate window, but the I don't like that we would have to monitor the websocket traffic to sniff the PDF url. 

I can tell you that it *is* something Overleaf devs have been working on a while ago:

https://www.overleaf.com/blog/overleafs-remote-hackathon-revisited-one-year

As for moving the pdf to the left, I'd have to look at the CSS they use, but if the process of fitting in the tab bar in the page is any indication this could prove troublesome as well.

**Comment by hrjakobsen** [comment]
Overleaf has now implemented this feature, and is currently beta testing it. I'll close this issue.
